import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import {LargeButtonOutline, RegularButtonOutline, SmallButtonOutline} from "../components/button_outline";
import {LargeButtonSolid, RegularButtonSolid, SmallButtonSolid} from "../components/buttons_solid";


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ksk-armada</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"/>
      </Head>

      <main className={styles.main}>
        <h1>ksk armada</h1>
      </main>
    </div>
  )
}
