import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import Invite from '../components/regular/invite';
import ShortAboutUs from '../components/regular/shortAboutUs';
import Group1 from '../components/home/group1';
import Group2 from '../components/home/group2';

const Home = () => {
  return (
    <>
      <Head>
        <title>ksk-armada</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.container}>  
      <main className={styles.main}>
        <Group1/>
        <Invite/>
        <Group2/> 
        <ShortAboutUs/>
      </main>
      </div>
    </>
  )
}
export default Home;