import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import Invite from '../components/regular/invite';

export default function Home() {
  return (
    <>
      <Head>
        <title>ksk-armada</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.container}>
      <Invite/> 
        <main className={styles.main}>
          
        </main>
      </div>
    </>
  )
}
